services:
  db_mysql:
    image: mysql
    ports:
      - 8000:80
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: credits
    volumes:
      - credit-app:/var/libs/mysql
  users:
    container_name: credit_users
    image: openjdk:17-alpine
    working_dir: /spring/credit_users
    volumes:
      - ./SimpleMicroservice-users:/spring/credit_users
    command: sh -c "./gradlew clean && ./gradlew build --no-build-cache && ./gradlew bootRun"
    ports:
      - 4000:8080
    environment:
      MYSQL_HOST: db_mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: users

volumes:
  credit-app: